### ISSUE TITLE
Rename PID package name

### ISSUE THREAD

**Issue by SuPeRMiNoR2** [OpenPrograms/mpmxyz-Programs#3]
So, apparently someone already had a package named pid. https://github.com/OpenPrograms/Kubuxu-Programs/blob/master/programs.cfg
I don't know why it was not causing issues until now, but one of them needs to be renamed to be able install pid properly. Possibly name this one mpmpid again?

**Comment by mpmxyz** [comment]
I renamed it to mpmpid.
Thank you for reporting!

**Comment by SuPeRMiNoR2** [comment]
Thanks, that should help clear up an installation bug where installing autopid installs the wrong version of pid, causing extreme confusion.
